Document: mindscape
Title: Debian mindscape Manual
Author: <insert document author here>
Abstract: This manual describes what mindscape is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mindscape/mindscape.sgml.gz

Format: postscript
Files: /usr/share/doc/mindscape/mindscape.ps.gz

Format: text
Files: /usr/share/doc/mindscape/mindscape.text.gz

Format: HTML
Index: /usr/share/doc/mindscape/html/index.html
Files: /usr/share/doc/mindscape/html/*.html
