var annotated_dup =
[
    [ "engine", null, [
      [ "Animation", "classengine_1_1_animation.html", "classengine_1_1_animation" ],
      [ "Audio", "classengine_1_1_audio.html", "classengine_1_1_audio" ],
      [ "Color", "structengine_1_1_color.html", "structengine_1_1_color" ],
      [ "Component", "classengine_1_1_component.html", "classengine_1_1_component" ],
      [ "Event", "classengine_1_1_event.html", "classengine_1_1_event" ],
      [ "EventHandler", "classengine_1_1_event_handler.html", "classengine_1_1_event_handler" ],
      [ "Game", "classengine_1_1_game.html", "classengine_1_1_game" ],
      [ "GameObject", "classengine_1_1_game_object.html", "classengine_1_1_game_object" ],
      [ "Hitbox", "classengine_1_1_hitbox.html", "classengine_1_1_hitbox" ],
      [ "Image", "classengine_1_1_image.html", "classengine_1_1_image" ],
      [ "KeyboardEvent", "classengine_1_1_keyboard_event.html", "classengine_1_1_keyboard_event" ],
      [ "Level", "classengine_1_1_level.html", "classengine_1_1_level" ],
      [ "Observable", "classengine_1_1_observable.html", "classengine_1_1_observable" ],
      [ "Observer", "classengine_1_1_observer.html", "classengine_1_1_observer" ],
      [ "Persistence", "classengine_1_1_persistence.html", "classengine_1_1_persistence" ],
      [ "PersistenceDat", "classengine_1_1_persistence_dat.html", "classengine_1_1_persistence_dat" ],
      [ "PersistenceMap", "classengine_1_1_persistence_map.html", "classengine_1_1_persistence_map" ],
      [ "Physics", "classengine_1_1_physics.html", "classengine_1_1_physics" ],
      [ "Scene", "classengine_1_1_scene.html", "classengine_1_1_scene" ],
      [ "StateMap", "classengine_1_1_state_map.html", "classengine_1_1_state_map" ],
      [ "Text", "classengine_1_1_text.html", "classengine_1_1_text" ],
      [ "Time", "classengine_1_1_time.html", "classengine_1_1_time" ],
      [ "Timer", "classengine_1_1_timer.html", "classengine_1_1_timer" ],
      [ "Translator", "classengine_1_1_translator.html", null ]
    ] ],
    [ "mindscape", null, [
      [ "Action", "classmindscape_1_1_action.html", "classmindscape_1_1_action" ],
      [ "Arm", "classmindscape_1_1_arm.html", "classmindscape_1_1_arm" ],
      [ "Background", "classmindscape_1_1_background.html", "classmindscape_1_1_background" ],
      [ "Boss", "classmindscape_1_1_boss.html", "classmindscape_1_1_boss" ],
      [ "Button", "classmindscape_1_1_button.html", "classmindscape_1_1_button" ],
      [ "Clown", "classmindscape_1_1_clown.html", "classmindscape_1_1_clown" ],
      [ "DarkGirl", "classmindscape_1_1_dark_girl.html", "classmindscape_1_1_dark_girl" ],
      [ "Enemy", "classmindscape_1_1_enemy.html", "classmindscape_1_1_enemy" ],
      [ "Fighter", "classmindscape_1_1_fighter.html", "classmindscape_1_1_fighter" ],
      [ "Fox", "classmindscape_1_1_fox.html", "classmindscape_1_1_fox" ],
      [ "GameObjectFactory", "classmindscape_1_1_game_object_factory.html", "classmindscape_1_1_game_object_factory" ],
      [ "Goop", "classmindscape_1_1_goop.html", "classmindscape_1_1_goop" ],
      [ "HudFox", "classmindscape_1_1_hud_fox.html", "classmindscape_1_1_hud_fox" ],
      [ "HudGirl", "classmindscape_1_1_hud_girl.html", "classmindscape_1_1_hud_girl" ],
      [ "LevelFactory", "classmindscape_1_1_level_factory.html", "classmindscape_1_1_level_factory" ],
      [ "LittleGirl", "classmindscape_1_1_little_girl.html", "classmindscape_1_1_little_girl" ],
      [ "MusicPlayer", "classmindscape_1_1_music_player.html", "classmindscape_1_1_music_player" ],
      [ "Platform", "classmindscape_1_1_platform.html", "classmindscape_1_1_platform" ],
      [ "Scorpion", "classmindscape_1_1_scorpion.html", "classmindscape_1_1_scorpion" ],
      [ "SelectArrow", "classmindscape_1_1_select_arrow.html", "classmindscape_1_1_select_arrow" ],
      [ "Spider", "classmindscape_1_1_spider.html", "classmindscape_1_1_spider" ],
      [ "Star", "classmindscape_1_1_star.html", "classmindscape_1_1_star" ],
      [ "Uncle", "classmindscape_1_1_uncle.html", "classmindscape_1_1_uncle" ]
    ] ],
    [ "Game", "class_game.html", null ],
    [ "GameEvent", "class_game_event.html", "class_game_event" ]
];